$(document).ready(function() {
	$('#${componentId}').popup({
        type: ${type},
        autoopen: ${autoopen},
        background: ${background},
        backgroundactive: ${backgroundactive},
        color: ${color},
        opacity: ${opacity},
        horizontal: ${horizontal},
        vertical: ${vertical},
        offsettop: ${offsettop},
        offsetleft: ${offsetleft},
        escape: ${escape},
        blur: ${blur},
        setzindex: ${setzindex},
        autozindex: ${autozindex},
        scrolllock: ${scrolllock},
        keepfocus: ${keepfocus},
        focuselement: ${focuselement},
        focusdelay: ${focusdelay},
        outline: ${outline},
        pagecontainer: ${pagecontainer},
        detach: ${detach},
        openelement: ${openelement},
        closeelement: ${closeelement},
        transition: ${transition},
        tooltipanchor: ${tooltipanchor},
        beforeopen: ${beforeopen},
        onclose: ${onclose},
        onopen: ${onopen},
        opentransitionend: ${opentransitionend},
        closetransitionend: ${closetransitionend}
    });
})